export const filterConfig = [
  {
    title: "Department",
    filterKey: "gender",
    items: [
      { title: "Unisex", filterValue: "Unisex" },
      { title: "Girls", filterValue: "Girls" },
      { title: "Women", filterValue: "Women" },
      { title: "Men", filterValue: "Men" },
      { title: "Boys", filterValue: "Boys" },
    ],
  },
  {
    title: "Categories",
    filterKey: "masterCategory",
    items: [
      { title: "Accessories", filterValue: "Accessories" },
      { title: "Apparel", filterValue: "Apparel" },
      { title: "Footwear", filterValue: "Footwear" },
      { title: "Personal Care", filterValue: "Personal Care" },
      { title: "Sporting Goods", filterValue: "Sporting Goods" },
      { title: "Free Items", filterValue: "Free Items" },
    ],
  },
  {
    title: "Category Type",
    filterKey: "subCategory",
    items: [
      { title: "Jewellery", filterValue: "Jewellery" },
      { title: "Gloves", filterValue: "Gloves" },
      { title: "Beauty Accessories", filterValue: "Beauty Accessories" },
      { title: "Apparel Set", filterValue: "Apparel Set" },
      { title: "Eyes", filterValue: "Eyes" },
      { title: "Water Bottle", filterValue: "Water Bottle" },
      { title: "Nails", filterValue: "Nails" },
      { title: "Cufflinks", filterValue: "Cufflinks" },
      { title: "Socks", filterValue: "Socks" },
      { title: "Ties", filterValue: "Ties" },
      { title: "Shoe Accessories", filterValue: "Shoe Accessories" },
      { title: "Skin", filterValue: "Skin" },
      { title: "Lips", filterValue: "Lips" },
      { title: "Eyewear", filterValue: "Eyewear" },
      { title: "Shoes", filterValue: "Shoes" },
      { title: "Flip Flops", filterValue: "Flip Flops" },
      { title: "Innerwear", filterValue: "Innerwear" },
      { title: "Belts", filterValue: "Belts" },
      { title: "Makeup", filterValue: "Makeup" },
      { title: "Bags", filterValue: "Bags" },
      { title: "Sports Accessories", filterValue: "Sports Accessories" },
      { title: "Saree", filterValue: "Saree" },
      { title: "Free Gifts", filterValue: "Free Gifts" },
      { title: "Bath and Body", filterValue: "Bath and Body" },
      { title: "Stoles", filterValue: "Stoles" },
      { title: "Topwear", filterValue: "Topwear" },
      { title: "Dress", filterValue: "Dress" },
      { title: "Fragrance", filterValue: "Fragrance" },
      { title: "Scarves", filterValue: "Scarves" },
      { title: "Wallets", filterValue: "Wallets" },
      { title: "Mufflers", filterValue: "Mufflers" },
      { title: "Watches", filterValue: "Watches" },
      { title: "Bottomwear", filterValue: "Bottomwear" },
      { title: "Sports Equipment", filterValue: "Sports Equipment" },
      { title: "Sandal", filterValue: "Sandal" },
      { title: "Skin Care", filterValue: "Skin Care" },
      { title: "Headwear", filterValue: "Headwear" },
      { title: "Loungewear and Nightwear", filterValue: "Loungewear and Nightwear" },
    ],
  },
  {
    title: "Season",
    filterKey: "season",
    items: [
      { title: "Winter", filterValue: "Winter" },
      { title: "Fall", filterValue: "Fall" },
      { title: "Summer", filterValue: "Summer" },
      { title: "Spring", filterValue: "Spring" },
    ],
  },
  {
    title: "Usage Type",
    filterKey: "usage",
    items: [
      { title: "Casual", filterValue: "Casual" },
      { title: "Formal", filterValue: "Formal" },
      { title: "Ethnic", filterValue: "Ethnic" },
      { title: "Party", filterValue: "Party" },
      { title: "NA", filterValue: "NA" },
      { title: "Travel", filterValue: "Travel" },
      { title: "Sports", filterValue: "Sports" },
      { title: "Smart Casual", filterValue: "Smart Casual" },
    ],
  },
  {
    title: "Max Price",
    filterKey: "maxPrice",
    items: [
      { title: "Up to $25", filterValue: "25" },
      { title: "Up to $50", filterValue: "50" },
      { title: "Up to $100", filterValue: "100" },
      { title: "Up to $200", filterValue: "200" },
    ],
  },
  {
    title: "Color",
    filterKey: "color",
    items: [
      { title: "Mauve", filterValue: "Mauve" },
      { title: "Multi", filterValue: "Multi" },
      { title: "Copper", filterValue: "Copper" },
      { title: "Brown", filterValue: "Brown" },
      { title: "Orange", filterValue: "Orange" },
      { title: "Rose", filterValue: "Rose" },
      { title: "Purple", filterValue: "Purple" },
      { title: "Grey", filterValue: "Grey" },
      { title: "Navy Blue", filterValue: "Navy Blue" },
      { title: "Tan", filterValue: "Tan" },
      { title: "Taupe", filterValue: "Taupe" },
      { title: "Yellow", filterValue: "Yellow" },
      { title: "Off White", filterValue: "Off White" },
      { title: "Olive", filterValue: "Olive" },
      { title: "Bronze", filterValue: "Bronze" },
      { title: "Metallic", filterValue: "Metallic" },
      { title: "Lavender", filterValue: "Lavender" },
      { title: "Sea Green", filterValue: "Sea Green" },
      { title: "Coffee Brown", filterValue: "Coffee Brown" },
      { title: "Skin", filterValue: "Skin" },
      { title: "Grey Melange", filterValue: "Grey Melange" },
      { title: "Mushroom Brown", filterValue: "Mushroom Brown" },
      { title: "Red", filterValue: "Red" },
      { title: "Mustard", filterValue: "Mustard" },
      { title: "Lime Green", filterValue: "Lime Green" },
      { title: "Silver", filterValue: "Silver" },
      { title: "Teal", filterValue: "Teal" },
      { title: "White", filterValue: "White" },
      { title: "Green", filterValue: "Green" },
      { title: "Rust", filterValue: "Rust" },
      { title: "Gold", filterValue: "Gold" },
      { title: "Black", filterValue: "Black" },
      { title: "Peach", filterValue: "Peach" },
      { title: "Blue", filterValue: "Blue" },
      { title: "Beige", filterValue: "Beige" },
      { title: "Cream", filterValue: "Cream" },
      { title: "Burgundy", filterValue: "Burgundy" },
      { title: "Maroon", filterValue: "Maroon" },
      { title: "Magenta", filterValue: "Magenta" },
      { title: "Pink", filterValue: "Pink" },
      { title: "Khaki", filterValue: "Khaki" },
      { title: "Steel", filterValue: "Steel" },
      { title: "Nude", filterValue: "Nude" },
      { title: "Turquoise Blue", filterValue: "Turquoise Blue" },
      { title: "Charcoal", filterValue: "Charcoal" },
    ],
  },
];